[package]
name = "ngv-opx-python"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "PyO3 Python bindings for ngv-opx."

[lib]
name = "ngv_opx"
crate-type = ["cdylib"]

[dependencies]
ngv-opx-core.workspace = true
ngv-opx-gpu.workspace = true
pyo3 = { version = "0.22", features = ["extension-module"] }
numpy = "0.22"
